name: Format
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: black
        uses: lgeiger/black-action@master
        with:
          args: .

      - name: Apply black formatting if reviewdog found formatting errors
        if: "${{ failure() }}"
        run: |
          black .

      - name: Commit black formatting results
        if: "${{ failure() }}"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":art: Format Python code with psf/black push"
